import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/sections/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-full md:w-[790px] mx-auto text-white text-center'>
        <h2 className='uppercase font-bold text-6xl leading-[5rem]'> Something awesome is coming soon </h2>
        <p className='text-[20px] font-light my-4'> Your all-in-one affiliate marketing tracking software <span className='font-medium'>track, automate</span> and <span className='font-medium'>optimize</span> your campaigns. </p>
      </div>

      <Footer/>
    </div>
  )
}
