import Head from 'next/head'
import Image from 'next/image'
import Input from '../components/elements/input';
import Button from '../components/elements/button'
import Footer from '../components/sections/footer'
import CountdownTimer from '../components/widgets/countdown-timer/countdown-timer';

export default function Home() {

  return (
    <div className='relative pt-20 pb-64 w-full lg:w-[1000px] mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className='relative w-full lg:w-[790px] mx-auto text-white text-center z-[100]'>
        <div className='w-4/6 md:w-2/6 mx-auto'>
          <Button label="Coming Soon" link="/comingsoon"/>
        </div>
        <div className='w-4/6 md:w-2/6 mx-auto my-10'>
          <Button label="Github" link="/comingsoon"/>
        </div>
      </section>
        

      <div className='absolute top-6 left-4 w-36 h-36 bg-gradient-to-b from-[#7F1E7B] to-[#19073B] rounded-full z-0'></div>
      <div className='absolute top-32 right-16 w-32 h-32 bg-gradient-to-b from-[#213F72] to-[#19073B] rounded-full'></div>
      <div className='absolute bottom-20 left-28 w-40 h-40 bg-gradient-to-b from-[#7F4129] to-[#1C0C28] rounded-full'></div>
    </div>
  )
}
